version: "3"
networks:
  wpsite:
volumes:
  db_data:

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - wpsite
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  # phpMyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    networks:
      - wpsite
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
  # Wordpress
  wordpress:
    image: wordpress
    depends_on:
      - db
    networks:
      - wpsite
    ports:
      - "8000:80"
    restart: always
    volumes: ['./storage:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

